# Generated by Django 3.2.7 on 2021-09-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('AP', 'APROBADO'), ('DN', 'DENEGADO'), ('ET', 'EN TRAMITE')], default='ET', max_length=10),
        ),
    ]
